### ISSUE TITLE
Link on documentation links to same page

### ISSUE THREAD

**Issue by jolamar** [indiana-university/rivet-react#144]
> I am looking at the documentation for Rivet React and I noticed that the link `Component Documentation and Style Guide` on the home page of `https://indiana-university.github.io/rivet-react` links to `https://indiana-university.github.io/rivet-react` (the same page) — is that intentional? (edited)

I added the documentation link to the repo's homepage so I propose we remove the links in the readme file that go to the documentation.

**Comment by jwbennet** [comment]
If we remove the link from the README it will also remove it from NPM:

https://www.npmjs.com/package/rivet-react

**Comment by jolamar** [comment]
True. I think having it linked a bunch is not a bad thing. Let's keep it.
