### ISSUE TITLE
HeaderIdentity/Dropdown: 'Unable to find node on an unmounted component'

### ISSUE THREAD

**Issue by nbannist** [indiana-university/rivet-react#155]
### Overview 

Trying out rivet-react and found that when I add children to a HeaderIdentity component it makes a dropdown. This dropdown can be opened just fine but when trying to close the resulting dropdown, react throws an error (included below) when clicking anywhere on the page. It looks like it has to do with events.

However, this error doesn't happen with the rivet-react documentation website, so I'm hoping it's something I'm doing incorrectly with setup or something and not an actual bug. I saw that the event delegation was changed in rivet 1.1.0, so I even tried rivet 1.0.0 but that didn't seem to work either.

### Simple code example
https://codesandbox.io/s/0kw4xy5wl

Steps:
1) open the identity dropdown
2) click anywhere on the page (even the identity dropdown)
3) you'll see the error (reiterated below) in the console (and as a page overlay)

### Error and Stack trace
```
Invariant Violation
Unable to find node on an unmounted component.

Stacktrace:
invariant
https://0kw4xy5wl.codesandbox.io/node_modules/fbjs/lib/invariant.js:42:15
findCurrentFiberUsingSlowPath
https://0kw4xy5wl.codesandbox.io/node_modules/react-dom/16.4.1/cjs/react-dom.development.js:3876:27
findCurrentHostFiber
https://0kw4xy5wl.codesandbox.io/node_modules/react-dom/16.4.1/cjs/react-dom.development.js:3886:23
findHostInstance
https://0kw4xy5wl.codesandbox.io/node_modules/react-dom/16.4.1/cjs/react-dom.development.js:16824:19
Object.findDOMNode
https://0kw4xy5wl.codesandbox.io/node_modules/react-dom/16.4.1/cjs/react-dom.development.js:17310:12
Dropdown._this.shouldToggleDropdown
https://0kw4xy5wl.codesandbox.io/node_modules/rivet-react/build/dist/components/Dropdown/Dropdown.js:48:40
Dropdown.handleClickOutside
https://0kw4xy5wl.codesandbox.io/node_modules/rivet-react/build/dist/components/Dropdown/Dropdown.js:97:27
HTMLDocument.eventHandler
https://0kw4xy5wl.codesandbox.io/node_modules/rivet-react/build/dist/components/util/AbstractUserActionEvent.js:34:13
```

**Comment by jwbennet** [comment]
You might try downgrading to React 16.4.x.  There is an issue where react-dom cannot find components mounted from different minor versions of react-dom and the easiest path forward for now is to match the minor version of React to what this library is using.

**Comment by nbannist** [comment]
That seemed to work in the code example. I'll try that in my project.

Thank you!

**Comment by nbannist** [comment]
I was using react and react-dom v16.5.2. Downgrading to 16.4.2 for both react and react-dom fixed the issue as indicated.

Thank you
