### ISSUE TITLE
hide attribute should work on any component not just Container

### ISSUE THREAD

**Issue by jolamar** [indiana-university/rivet-react#156]
https://indiana-university.github.io/rivet-react/#/Utilities?id=visibility

Looks like `hide` can only be used on the container element.

**Comment by jwbennet** [comment]
This looks to be more a problem with the core Rivet CSS than a problem with this library, though if you have a specific case where you're finding the `rvt-hide-*` properties are not being applied it would be helpful to know.

**Comment by jolamar** [comment]
I must have been having a brain fart and trying to use it on a non-Rivet React element (such as a regular div). Anyways it's working now.
