### ISSUE TITLE
License Mismatch in package.json vs. LICENSE file

### ISSUE THREAD

**Issue by burnumd** [indiana-university/rivet-react#159]
The License specified in the project's [package.json](https://github.com/indiana-university/rivet-react/blob/develop/package.json#L6) file is MIT, but the license specified by [LICENSE](https://github.com/indiana-university/rivet-react/blob/develop/LICENSE) is Apache 2.0

**Comment by burnumd** [comment]
Neither license, it should be mentioned, is in accordance with the [IU Open Source Guidelines](https://indiana-university.github.io/) requirement that projects use BSD-3.

**Comment by jhoerr** [comment]
Fixed in #173
