### ISSUE TITLE
Add ErrorBoundary to Rivetize function

### ISSUE THREAD

**Issue by burnumd** [indiana-university/rivet-react#353]
When a "Rivetized" component has a required property that is not provided, the component should throw an error. That error should be handled by an error boundary component. We can wrap rivetized components in that error boundary and accept an optional fallback to render when the wrapped component throws an error.

**Comment by johglove** [comment]
Closing because after discussion, we found the solution would be better served by pointing end users of the library to Error Boundary documentation for their components which have more complex business logic.

**Comment by burnumd** [comment]
Closing because after discussion, we found the solution would be better served by pointing end users of the library to Error Boundary documentation for their components which have more complex business logic.
