### ISSUE TITLE
Console warnings from Rivet 2 components

### ISSUE THREAD

**Issue by jkneal** [indiana-university/rivet-react#428]
Getting the following warnings in the console in cases where I think the usage is valid:

**Didn’t pass logoutClick to HeaderAvatar, is it required?**

react-jsx-dev-runtime.development.js:87 Warning: Failed prop type: Header.Avatar: prop type `logoutClick` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.This often happens because of typos such as `PropTypes.function` instead of `PropTypes.func`.

**Passed HeaderAvatar for the label to BaseHeaderMenu**

react-jsx-dev-runtime.development.js:87 Warning: Failed prop type: Invalid prop `label` of type `object` supplied to `BaseHeaderMenu`, expected `string`.

**Passing columnWidth={2} to Col**

react-jsx-dev-runtime.development.js:87 Warning: Failed prop type: Invalid prop `columnWidth` of value `2` supplied to `Col`, expected one of ["1","2","3","4","5","6","7","8","9","10","11","12"].

**Comment by johglove** [comment]
https://github.com/indiana-university/rivet-react/pull/433
