### ISSUE TITLE
Using "role" as prop name conflicts with ARIA attribute

### ISSUE THREAD

**Issue by athill** [indiana-university/rivet-react#448]
The `Badge` and `Button` components both have a `role` prop that can take the value "secondary". When linting with the `jsx/a11y` plugin, this results in the following error: 
```shell
 error  Elements with ARIA roles must use a valid, non-abstract ARIA role
```

We should change the name of this prop in these components to something that does not conflict. Maybe `rivetrole`?

**Comment by burnumd** [comment]
I think changing it to something like `type` may be the simplest change here. I worry that `rivetrole` may get confused with an ARIA role specific to Rivet.

**Comment by burnumd** [comment]
I opened a PR using `modifier` as the prop since that's what we actually use in `Button` (though its PropType calls it `role`).
