### ISSUE TITLE
List child wrapping doesn't specify keys, causing console errors

### ISSUE THREAD

**Issue by burnumd** [indiana-university/rivet-react#56]
Currently, `List` supports children which are numbers, strings, or `<li>` elements, or some combination of those things. It then wraps any children which aren't list items, but this modification renders them as though they are an array and also doesn't specify keys for the mutated child elements.

**Comment by burnumd** [comment]
I think the comprehensive approach to solving this issue is just to only accept `<li>` elements as children of a list, since that HTMLElement already type-checks its children since otherwise the List component ought to be supporting `React.ReactNode` and the keying becomes much more complicated.

**Comment by jwbennet** [comment]
Can you provide a quick example that generates an error here?  The following works fine for me and I'm not seeing any issues in the console:

```jsx
<List> 
  <a href="#0">Foo</a>
  <a href="#0">Bar</a>
  <a href="#0">Baz</a>
</List>
```

**Comment by burnumd** [comment]
I can reproduce it with 

```jsx
<List>
    {[<a href="#">List Item One</a>, <a href="#">List Item Two</a>]}
</List>
```

But it looks like the error in that case comes from the `asListItems` function iterating over the unkeyed array passed in, which is a valid error. I still think the current implementation (which relies on using auto-generated keys on the wrapping `li` elements) can cause performance issues once this is out in the wild since the entire list will need to re-render whenever children change instead of just the modified children, but that's a separate issue (and one I'd want to gather data on before acting on it).
