### ISSUE TITLE
Chat about release processes

### ISSUE THREAD

**Issue by levimcg** [indiana-university/rivet-react#70]
Hey, friends

I've seen some back and forth about doing a release soon. When we move the Rivet core library over to github.com we're planing to re-evaluate our current release process, and move our CI/build process stuff over to Travis/Circle/whatever's cool right now 😄 

I though it could be nice to chat about how you all are planing to do releases, and maybe try to follow similar process/use similar tools where possible.

If anyone is interested, I'd be happy to set up a face-to-face sometime soon.

**Comment by jhoerr** [comment]
Hey Levi, we recently moved from Travis to Circle CI. I'm happy to talk over the nuts and bolts with you.

**Comment by jhoerr** [comment]
Per the release chatter, I think our plan at the moment is something like:
* 0.3.0: Work to date, documentation, style guide
* 0.4.0: Upgrade to TS 3.0, feature parity with Rivet 1.0 (Tabs)
* 1.0.0: Integrate feedback from user testing
