### ISSUE TITLE
Inconsistent use of dot notation in component names

### ISSUE THREAD

**Issue by jhoerr** [indiana-university/rivet-react#81]
When are using dot notation inconsistently when naming components. I'd like to see if we can come to some agreement on a unified approach. I'm tagging this as for Milestone 0.3.0 because it will be an (avoidable) breaking change if we wait.

**Problem Statement**

There are several complex components, including Header and Modal, in which we use dot notation to express a hierarchical relationship. There are two primary benefits to this approach: 

1. it simplifies `import` statements;
2. it visually implies that e.g. `Modal.Body` necessarily 'goes with'  a `Modal` and should only be used within a `Modal`.  That is, a `Modal.Body` is not intended to be used as a standalone component.

```jsx
import Modal from './Modal'

<Modal>
  <Modal.Body>...</Modal.Body>
  <Modal.Controls>...</Modal.Controls>
</Modal>

import Header from './Header'

<Header>
  <Header.Identity />
  <Header.Navigation>
    <Header.Menu>...</Header.Menu>
  </Header.Navigation>
</Header>
```

There are multiple components that do not use dot notation but are are similarly structured in that the 'child' components should not be used without a corresponding 'parent' component. Examples include `Dropdown`/`DropdownGroup`, and `Container`/`Grid`/`Col`:

```jsx
<Dropdown>
  <DropdownGroup>...</DropdownGroup>
</Dropdown>

<Container>
  <Grid>
    <Col>...</Col>
  </Grid>
</Container>
```

Another example is `Button`/`ButtonGroup`/`SegmentedButton`, though the structure is slightly different. In this case, the 'parent' component should not be used absent a corresponding 'child' component:

```jsx
<ButtonGroup>
  <Button />
  <Button />
</ButtonGroup>

<SegmentedButton>
  <Button />
  <Button />
</SegmentedButton>
```

**Proposed Solution 1: Strictly use dot notation everywhere.**

Pros: simplified imports across the board, and a clear indication of the 'primary' component in the hierarchy.
Cons: `rivetize` may not be able to maintain the statically-applied dotted children (see [Header](https://github.com/indiana-university/rivet-react/blob/develop/src/components/Header/Header.tsx#L41-L43) for example of this.

Suggested changes:

```jsx
<Dropdown>
  <Dropdown.Group>...</Dropdown.Group>
</Dropdown>

<Button.Group>
  <Button />
  <Button />
</Button.Group>.

<Container>
  <Container.Grid>
    <Container.Col>...</Container.Col>
  </Container.Grid>
</Container>
```

**Proposed Solution 2: Remove dot notation from Header and Modal**

Pros: `rivetize` continues to work without issue.
Cons: More verbose imports.

Suggested changes:

```jsx
import Modal, ModalBody, ModalControls from './Modal'

<Modal>
  <ModalBody>...</ModalBody>
  <ModalControls>...</ModalControls>
</Modal>

import Header, HeaderIdentity, HeaderNavigation, HeaderMenu from './Header'

<Header>
  <HeaderIdentity />
  <HeaderNavigation>
    <HeaderMenu>...</HeaderMenu>
  </HeaderNavigation>
</Header>
```

**Comment by athill** [comment]
For the record, some of the exact same inconsistencies exist within [react-bootstrap](https://react-bootstrap.github.io/components/) and I think they arguably make sense. 
* `ButtonGroup` is not a sub-component of `Button` and `ButtonGroup.Button` makes no sense, because a `Button` can exist outside a `ButtonGroup`
* `Container.Grid`, etc. are, imo, overly long for practical use. The other difference is that  `Container`s can exist throughout a page, some using `Grid` and `Col` and some not. This is different in my mind, especially from `Modal`, which is expected to have a `Modal.Body` and `Modal.Footer`. I admit my logic is not particularly compelling on this point.

**Comment by burnumd** [comment]
I like Andy's approach of only using dot case when the component is a required child of the parent. Can you explain what technical details prevent `rivetize` from working on child components? I'm not understanding what's not working about Rivetize from the link to those lines in `Header`.

**Comment by jhoerr** [comment]
@athill wrote: 

> For the record, some of the exact same inconsistencies exist within react-bootstrap and I think they arguably make sense.

James and I were discussing this yesterday, and we noticed that [Nav](https://react-bootstrap.github.io/components/navs/) doesn't use the dot notation. James mentioned that it did before, so maybe they've changed it? Are you aware of other examples?

> ButtonGroup is not a sub-component of Button and ButtonGroup.Button makes no sense, because a Button can exist outside a ButtonGroup.

I agree with you. Let me see if I can make the argument more abstractly: with `Modal` and `Modal.Body`, we are try to impress on the consumer that you cannot (or should not) create a Modal.Body outside of a Modal and that it should not be used as a standalone component. The same argument applies to ButtonGroup: there is no scenario in which you should use a ButtonGroup without a corresponding Button. The Button is the `primary` component, and the ButtonGroup is a `secondary` component that adds value to the primary, just as the Modal is the 'primary' and the Modal.Body is the `secondary`.  

> Container.Grid, etc. are, imo, overly long for practical use.

I'm flexible on the names. I'm primarily interested in a consistent convention.


@burnumd wrote:

> I like Andy's approach of only using dot case when the component is a required child of the parent.

By way of counter example, both `Header.Identity` nor `Header.Navigation` are optional.

> I'm not understanding what's not working about Rivetize from the link to those lines in Header.

 Rivetize can't pass along the statically-applied `Navigation` and `Identity` properties on `Header`. They effectively get ignored from the emitted component. If you pass a dotted component through `rivetize` you'll notice that the sub components are not rendered. We avoided this problem with Header and Modal because they don't need to be `rivetize`d.

**Comment by athill** [comment]
I'm starting to think the cleanest way forward might be to drop the dot notation altogether.

**Comment by jhoerr** [comment]
After conversing with @burnumd and @jwbennet we've resolved to remove the dot notation.
